# Generated by Django 4.0.1 on 2022-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_best_selling',
            field=models.BooleanField(null=True),
        ),
    ]
